"""add warm

Revision ID: fde66d668aa4
Revises: b22dcba0e918
Create Date: 2024-08-28 17:27:58.597274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fde66d668aa4'
down_revision: Union[str, None] = 'b22dcba0e918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warm',
    sa.Column('electro_unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('plan', sa.Float(), nullable=False),
    sa.Column('fact', sa.Float(), nullable=False),
    sa.Column('plane_coast', sa.Float(), nullable=False),
    sa.Column('fact_coast', sa.Float(), nullable=False),
    sa.Column('delta_values', sa.Float(), nullable=False),
    sa.Column('delta_coast', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warm')
    # ### end Alembic commands ###
