"""add ondelete cascade to data if remove device

Revision ID: 2dfd51025234
Revises: fde66d668aa4
Create Date: 2025-10-28 00:36:32.079843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dfd51025234'
down_revision: Union[str, None] = 'fde66d668aa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('data_device_sync_id_fkey'), 'data', type_='foreignkey')
    op.create_foreign_key(None, 'data', 'devices', ['device_sync_id'], ['sync_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.create_foreign_key(op.f('data_device_sync_id_fkey'), 'data', 'devices', ['device_sync_id'], ['sync_id'])
    # ### end Alembic commands ###
